config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registratons: "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"

  resources :categories do
    resources :tasks do
      collection do 
        get 'remove_all'
      end
    end
  end

  # get '/categories' => 'categories#index'

  # get '/categories/:id' => 'categories#show'

  # post '/categories' => 'categories#create'

  # get '/categories/new' => 'categories#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_many :tasks
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    validates :name, presence: true
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :tasks, through: :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :user

  def user
    @user = User.find(current_user.id)
    @tasks = @user.tasks.where("deadline = ?", Date.today.midnight)
  end

  def index
    # render json: {success: true}, status:
    @categories = Category.all
  end

  def show
    @category = Category.find(params['id'])
    unless @category.user_id == current_user.id
      redirect_to categories_path
    end
  end

  def create
    @categories = Category.all
    @category = @user.categories.new(category_params)

    if @category.save
      redirect_to @category
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @categories = Category.all
    @category = Category.new
  end

  def edit
    @categories = Category.all
    @category = Category.find(params[:id])
  end

  def update
    @categories = Category.all
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :user

  def user
    @user = User.find(current_user.id)
  end
  
  def new
    @category = Category.find(params[:category_id])
    @task = Task.new
  end

  def create
    @category = Category.find(params[:category_id])
    @task = @category.tasks.create(task_params)
    redirect_to category_path(@category)
  end

  def destroy
    @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])
    @task.destroy
    redirect_to category_tasks_path(@category)
    # respond_to do |format|
    #   format.js {render inline: "location.reload();" }
    # end
  end

  def edit
    @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @task = @category.tasks.find(params[:id])
    @task.update(task_params)
    redirect_to category_path(@category)
  end

  def remove_all
    @category = Category.find(params[:category_id])
    Task.delete_all
    redirect_to category_path(@category), status: 303
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :deadline)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_categorybg.html.erb
<%= render "navbar", category: @category, user: @user %>
<div class="d-flex justify-content-center">
  <div class="position-absolute top-50 start-50 translate-middle">
    <div class="d-flex justify-content-center">
      <p class="notice" style="color: green"><%= notice %> </p>
    </div>
    <%= render "deadline", category: @category, user: @user, task: @task %>
    <div class="d-flex justify-content-center">
      <%= link_to "Create New Category +", new_category_path, :class => "btn btn-primary" %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Category</th>
          <th scope="col" class="text-center">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @user.categories.each do |category| %>
          <% if !!category.id %>
            <tr>
              <td><%= category.name %></td>
              <td>
                <div class="row">
                  <div class="col-sm">
                    <%= link_to "View", category, :class => "btn btn-light"
                 %>
                  </div>
                  <div class="col-sm">
                    <%= link_to "Edit", edit_category_path(category), :class => "btn-warning btn", :method => "get" %>
                  </div>
                  <div class="col-sm">
                    <%= link_to "Delete", category_path(category), :class => "btn-danger btn", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/_deadline.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Deadline Today</th>
      <th scope="col" class="">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td>
          <div class="row">
            <div class="col-sm">
              <%= link_to "Delete", [task.category, task], :class => "btn btn-danger", data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
  <div class="modal-body">
    <p><%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control" %>
      <% @category.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %></p>
  </div>
  <div class="modal-footer">
    <%= form.submit :Submit, class: "btn btn-primary" %>
    <%= link_to "back", categories_path, :class => "btn btn-secondary", :method => "get", :type => "button" %>
  </div>
<% end %>

app/views/categories/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand px-3" href="#">To Do List</a>
  <div class="navbar-collapse d-flex justify-content-end">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#"><%= @user.email %></a>
      </li>
    </ul>
    <span class="navbar-text px-3">
      <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
    </span>
  </div>
</nav>

app/views/categories/_taskbg.html.erb
<%= render "categories/navbar", category: @category, user: @user %>
<div class="container mt-4">
<div class="d-flex align-items-center">
<%= button_to "<", categories_path, :class => "btn btn-light", :method => "get" %>
<h1><%= @category.name %></h1>
</div>

<%= button_to "Create Task +", new_category_task_path(@category.id), :class => "btn-primary btn", :method => "get" %>
<%= link_to "Delete All", remove_all_category_tasks_path(@category.id), :class => "btn-warning btn", data: {
                turbo_confirm: "Are you sure to delete all?"
              } %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Deadline</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
<%= render @category.tasks %>
</tbody>
</table>
</div>

app/views/categories/edit.html.erb
<div class="container">
  <%= render "categorybg", category: @category %>
  <div class="modal" tabindex="-1" role="dialog" style="display: block; background-color: rgb(0,0,0,.5)">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Category Name</h5>
      </div>
<%= render "form", category: @category %>
    </div>
  </div>
</div>
</div>

app/views/categories/index.html.erb
<%= render "categorybg", category: @category, user: @user %>

app/views/categories/new.html.erb
<div class="container">
  <%= render "categorybg", category: @category %>
  <div class="modal" tabindex="-1" role="dialog" style="display: block; background-color: rgb(0,0,0,.5)">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Create New Category</h5>
      </div>
<%= render "form", category: @category %>
    </div>
  </div>
</div>
</div>

app/views/categories/show.html.erb
<%= render "taskbg", category: @category %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [ @category, @task ] do |form| %>
 <div class="modal-body">
        <p><div class="form-group">
      <%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %><br>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :deadline %><br>
      <%= form.date_field :deadline, class: "form-control" %>
    </div></p>
      </div>
      <div class="modal-footer">
        <%= form.submit :Submit, class: "btn btn-primary" %>
        <%= link_to "Back", @category, :class => "btn btn-secondary"
                 %>
      </div>   
    <p>
    </p>
  <% end %>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.name %></td>
  <td><%= task.description %></td>
  <td><%= task.deadline %></td>
  <td>
    <div class="row">
      <div class="col-sm">
      
        <%= link_to "Delete Task", [task.category, task], :class => "btn btn-danger", data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              } %>
             
      </div>
      <div class="col-sm">
        <%= button_to "Edit Task", edit_category_task_path(@category, task), :method => "get", :class => "btn btn-warning" %>
      </div>
    </div>
  </td>
</div>

app/views/tasks/edit.html.erb
<%= render "categories/taskbg", category: @category %>

<div class="container">
<div class="modal" tabindex="-1" role="dialog" style="display: block; background-color: rgb(0,0,0,.5)">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Task</h5>
      </div>
      <%= render "form" %>
    </div>
  </div>
</div>
</div>

app/views/tasks/new.html.erb
<%= render "categories/taskbg", category: @category %>

<div class="container">
<div class="modal" tabindex="-1" role="dialog" style="display: block; background-color: rgb(0,0,0,.5)">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Create Task</h5>
      </div>
      <%= render "form" %>
    </div>
  </div>
</div>
</div>